Add JMESpath for external source
legalthings/legalform-js pull request #35
Opened 2017-04-19 19:48 UTC by JohnConnor1969

2017-04-20 22:59 UTC, jasny requested changes
* Please add a unit test for this.
* Please add a new select field to the demo that uses jmespath.

2017-04-20 22:59 UTC, jasny commented on js/demo/demo.js
> +                        "jmespath" : "",
Is it required to have this property? That would mean all existing templates would break. Better not add it to the demo in cases it isn't used.

2017-04-20 23:01 UTC, JohnConnor1969 commented on js/demo/demo.js
> +                        "jmespath" : "",
is it not required
nothing to be broke

2017-04-23 22:30 UTC, jasny approved these changes

2017-04-23 22:30 UTC, merged