updated material version
legalthings/legalform-js pull request #80
Opened 2017-11-23 14:41 UTC by MitchelKerckhaert

Updated bootstrap-material-design to version 4.0.2. Looks like this removes most performance issues.

2017-11-24 10:47 UTC, Sarfaraaz requested changes
Unfortunately it's not as simple as just increasing the version.
Upgrading from v3 to v4 introduces a lot of breaking changes (as described [here](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/migration/)), let alone upgrading from 0.5.

2017-12-12 14:14 UTC, MitchelKerckhaert commented
I kept the floating labels. The collision between the label and the input field should not show up, because we should stay away from long labels and use descriptive text instead.

2017-12-18 15:47 UTC, Sarfaraaz commented
## Description
Floating labels were removed because the libraries we use don't compliment each other very well. Selectized selects would have the label float back as a placeholder.

## Preview
![image](https://user-images.githubusercontent.com/2484595/34114422-0a53b4d0-e413-11e7-8e84-7398236576c4.png)

2017-12-18 16:19 UTC, Sarfaraaz approved these changes

2017-12-18 16:21 UTC, merged